(function() {var implementors = {
"oxc_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"oxc_parser/enum.Kind.html\" title=\"enum oxc_parser::Kind\">Kind</a>"]],
"ssc_ast":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"ssc_ast/ast/enum.Namespace.html\" title=\"enum ssc_ast::ast::Namespace\">Namespace</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_ast/struct.Trivias.html\" title=\"struct ssc_ast::Trivias\">Trivias</a>"]],
"ssc_codegen":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_codegen/struct.CodegenOptions.html\" title=\"struct ssc_codegen::CodegenOptions\">CodegenOptions</a>"]],
"ssc_css_analyzer":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_css_analyzer/node/struct.AstNodes.html\" title=\"struct ssc_css_analyzer::node::AstNodes\">AstNodes</a>&lt;'a&gt;"],["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_css_analyzer/struct.Analyzer.html\" title=\"struct ssc_css_analyzer::Analyzer\">Analyzer</a>&lt;'a&gt;"]],
"ssc_css_ast":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_css_ast/struct.Trivias.html\" title=\"struct ssc_css_ast::Trivias\">Trivias</a>"]],
"ssc_css_codegen":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_css_codegen/struct.CodegenOptions.html\" title=\"struct ssc_css_codegen::CodegenOptions\">CodegenOptions</a>"]],
"ssc_css_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"ssc_css_parser/enum.Kind.html\" title=\"enum ssc_css_parser::Kind\">Kind</a>"]],
"ssc_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"ssc_parser/enum.Kind.html\" title=\"enum ssc_parser::Kind\">Kind</a>"]],
"ssc_parser_wasm":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_parser_wasm/struct.Diagnostic.html\" title=\"struct ssc_parser_wasm::Diagnostic\">Diagnostic</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_parser_wasm/struct.ParseResult.html\" title=\"struct ssc_parser_wasm::ParseResult\">ParseResult</a>"]],
"ssc_wasm":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_wasm/struct.Diagnostic.html\" title=\"struct ssc_wasm::Diagnostic\">Diagnostic</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ssc_wasm/struct.Ssc.html\" title=\"struct ssc_wasm::Ssc\">Ssc</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()