/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParseResult {
  root: string
  comments: Array<Comment>
  errors: Array<string>
}
export interface Comment {
  value: string
  start: number
  end: number
}
/**
 * Parse without returning anything.
 * This is for benchmark purposes such as measuring napi communication overhead.
 *
 * # Panics
 *
 * * File extension is invalid
 * * Serde JSON serialization
 */
export function parseWithoutReturn(sourceText: string): void
/**
 * # Panics
 *
 * * File extension is invalid
 * * Serde JSON serialization
 */
export function parseSync(sourceText: string): ParseResult
/**
 * # Panics
 *
 * * Tokio crashes
 */
export function parseAsync(sourceText: string): Promise<ParseResult>
